# Generated by Django 4.2.16 on 2026-05-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('rank', models.CharField(db_index=True, default='no rank', max_length=50)),
                ('rank_raw', models.CharField(db_index=True, default='no rank', max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pathogen_identification.taxon')),
            ],
        ),
    ]
