# Generated by Django 4.2.16 on 2026-03-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(blank=True, max_length=100, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.runmain')),
            ],
            options={
                'ordering': ['run'],
            },
        ),
        migrations.CreateModel(
            name='ClassifierOutputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('classifier_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.classifieroutput')),
            ],
            options={
                'ordering': ['classifier_output'],
            },
        ),
    ]
