# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='windows_covered',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
