# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-14 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='full_path',
        ),
    ]
