# Generated by Django 4.2.16 on 2026-06-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0002_referencesource_lineage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgroup',
            name='main_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.taxon'),
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='main_species_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TelevirRunQcStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_reports', models.CharField(blank=True, max_length=1000, null=True)),
                ('input_reads', models.IntegerField(blank=True, null=True)),
                ('output_reads', models.IntegerField(blank=True, default=0, null=True)),
                ('output_reads_percent', models.FloatField(blank=True, default=0, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.runmain')),
            ],
        ),
    ]
