# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0002_remove_projects_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='technology',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Technology'),
        ),
    ]
