# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0002_finalreport_windows_covered'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencemap_main',
            name='mapped_subset_r1_fasta',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='referencemap_main',
            name='mapped_subset_r2_fasta',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
