# Generated by Django 4.2.16 on 2026-06-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0003_reportgroup_main_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencetaxid',
            name='tax_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_species', to='pathogen_identification.taxon'),
        ),
    ]
