# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0003_auto_20221123_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencemap_main',
            name='vcf',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
