# Generated by Django 4.2.16 on 2026-04-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0003_projecttag_projecttagassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttag',
            old_name='tag',
            new_name='name',
        ),
    ]
