# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0029_remove_sample_identify_virus'),
        ('pathogen_identification', '0003_projects_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIProject_Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_extended', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('combinations', models.IntegerField(blank=True, null=True)),
                ('input', models.TextField(blank=True, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('report', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='uploaded date')),
                ('is_finished', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('is_mask_consensus_sequences', models.BooleanField(default=False)),
                ('alert_first_level', models.IntegerField(default=0)),
                ('alert_second_level', models.IntegerField(default=0)),
                ('seq_name_all_consensus', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted_in_file_system', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Date attached')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.Projects')),
            ],
            options={
                'ordering': ['project__id', '-creation_date'],
            },
        ),
        migrations.RemoveField(
            model_name='sample',
            name='project',
        ),
        migrations.AlterField(
            model_name='contigclassification',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='qc_report',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='readclassification',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='referencemap_main',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='runassembly',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='rundetail',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='runindex',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managing_files.Sample'),
        ),
        migrations.AlterField(
            model_name='runmain',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='runremapmain',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AlterField(
            model_name='sampleqc',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AddField(
            model_name='piproject_sample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managing_files.Sample'),
        ),
    ]
