# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0004_referencemap_main_vcf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalreport',
            name='description',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
