# Generated by Django 4.2.16 on 2026-04-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0004_rename_tag_projecttag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_error_rate', models.FloatField(blank=True, null=True)),
                ('error_rate_available', models.BooleanField(default=False)),
                ('avg_quality', models.FloatField(blank=True, null=True)),
                ('avg_quiality_available', models.BooleanField(default=False)),
                ('max_mapped_proportion', models.FloatField(blank=True, null=True)),
                ('max_coverage', models.FloatField(blank=True, null=True)),
                ('max_windows_covered', models.FloatField(blank=True, null=True)),
                ('tree_plot_path', models.CharField(blank=True, max_length=200, null=True)),
                ('tree_plot_exists', models.BooleanField(default=False)),
                ('overlap_heatmap_path', models.CharField(blank=True, max_length=200, null=True)),
                ('overlap_heatmap_exists', models.BooleanField(default=False)),
                ('overlap_pca_path', models.CharField(blank=True, max_length=200, null=True)),
                ('overlap_pca_exists', models.BooleanField(default=False)),
                ('reports_available', models.BooleanField(default=False)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.runmain')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.piproject_sample')),
            ],
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_counts', models.IntegerField(blank=True, null=True)),
                ('private_counts', models.IntegerField(blank=True, null=True)),
                ('private_counts_exist', models.BooleanField(default=False)),
                ('shared_proportion', models.FloatField(blank=True, null=True)),
                ('private_propotion', models.FloatField(blank=True, null=True)),
                ('max_private_reads', models.IntegerField(blank=True, null=True)),
                ('max_coverage', models.FloatField(blank=True, null=True)),
                ('analysis_empty', models.BooleanField(default=False)),
                ('has_multiple', models.BooleanField(default=False)),
                ('toggle', models.CharField(blank=True, max_length=100, null=True)),
                ('aggregator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.reportaggregate')),
                ('reports', models.ManyToManyField(blank=True, related_name='aggregated_reports', to='pathogen_identification.finalreport')),
            ],
        ),
    ]
