# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0004_auto_20220815_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piproject_sample',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_samples', to='pathogen_identification.Projects'),
        ),
    ]
