# Generated by Django 4.2.16 on 2026-06-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0004_referencetaxid_tax_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='televirrunqcstack',
            name='performed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='televirrunqcstack',
            name='qc_reports',
        ),
        migrations.CreateModel(
            name='LeafParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=200, null=True)),
                ('software_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parameter_value', models.CharField(blank=True, max_length=200, null=True)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.softwaretreenode')),
            ],
            options={
                'ordering': ['leaf', 'module', 'software_name', 'parameter_name'],
            },
        ),
        migrations.AddField(
            model_name='televirrunqcstack',
            name='qc_reports',
            field=models.ManyToManyField(blank=True, to='pathogen_identification.televirrunqc'),
        ),
    ]
