# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-26 15:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0012_parameter_is_to_run"),
        ("managing_files", "0030_reference_specie_tag"),
        ("pathogen_identification", "0005_auto_20220925_1154"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_index", models.SmallIntegerField(default=-1)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.Parameter",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pathogen_identification.Projects",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managing_files.Sample",
                    ),
                ),
            ],
        ),
    ]
