# Generated by Django 4.2.16 on 2026-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0005_televirrunqcstack_performed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawreferencecompoundmodel',
            name='contig_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawreferencecompoundmodel',
            name='read_counts',
            field=models.IntegerField(default=0),
        ),
    ]
