# Generated by Django 4.2.16 on 2026-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0005_reportaggregate_reportgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportaggregate',
            old_name='avg_quality',
            new_name='max_quality_avg',
        ),
        migrations.RenameField(
            model_name='reportaggregate',
            old_name='avg_quiality_available',
            new_name='quality_avg_available',
        ),
        migrations.AddField(
            model_name='reportaggregate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
