# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0006_auto_20221129_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreference',
            name='counts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
