# Generated by Django 4.2.16 on 2026-10-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0006_rawreferencecompoundmodel_contig_counts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nodes', models.ManyToManyField(blank=True, to='pathogen_identification.softwaretreenode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.projects')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
