# Generated by Django 4.2.16 on 2026-04-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0006_rename_avg_quality_reportaggregate_max_quality_avg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportgroup',
            old_name='private_propotion',
            new_name='private_proportion',
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='clade_heatmap_json',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='private_reads_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GroupReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_reads', models.IntegerField(blank=True, null=True)),
                ('data_exists', models.BooleanField(default=False)),
                ('found_in', models.ManyToManyField(blank=True, related_name='compound_runs', to='pathogen_identification.runmain')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.finalreport')),
                ('report_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.reportgroup')),
            ],
        ),
    ]
