# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0006_parameterset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Software name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Software_tree_nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Software name')),
                ('node_type', models.SmallIntegerField(default=0)),
                ('node_place', models.SmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pathogen_identification.Software_tree_nodes')),
                ('software_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.Software_tree')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='project',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='set_index',
        ),
    ]
