# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-03 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0007_auto_20221130_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['name', '-creation_date']},
        ),
    ]
