# Generated by Django 4.2.16 on 2026-04-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0007_rename_private_propotion_reportgroup_private_proportion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaggregate',
            name='shared_proportion_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportaggregate',
            name='sort_performed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportgroup',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_groups', to='pathogen_identification.reportaggregate'),
        ),
    ]
