# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-29 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathogen_identification', '0007_auto_20220928_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_index', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Software name')),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'global_index'],
            },
        ),
        migrations.RenameModel(
            old_name='Software_tree_nodes',
            new_name='SoftwareTree_nodes',
        ),
        migrations.DeleteModel(
            name='Software_tree',
        ),
        migrations.AlterField(
            model_name='softwaretree_nodes',
            name='software_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.SoftwareTree'),
        ),
    ]
