# Generated by Django 4.2.16 on 2026-10-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0007_runbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleBatchRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.runbatch')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.piproject_sample')),
            ],
            options={
                'ordering': ['-date_registered'],
            },
        ),
    ]
