# Generated by Django 4.2.16 on 2026-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0008_reportaggregate_shared_proportion_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaggregate',
            name='runs',
            field=models.ManyToManyField(blank=True, related_name='aggregated_runs', to='pathogen_identification.runmain'),
        ),
    ]
