# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-30 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0008_auto_20220929_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaretree_nodes',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
