# Generated by Django 4.2.16 on 2026-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0008_samplebatchregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreference',
            name='status',
            field=models.IntegerField(choices=[(0, 'Mapped'), (1, 'Unmapped'), (2, 'Mapping'), (3, 'Fail'), (4, 'Missing')], default=1),
        ),
    ]
