# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0008_auto_20221203_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
