# Generated by Django 4.2.16 on 2026-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0009_alter_rawreference_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='runremapmain',
            name='missing_log',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
