# Generated by Django 4.2.16 on 2026-04-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0009_reportaggregate_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportgroup',
            name='clade_heatmap_json',
        ),
        migrations.AddField(
            model_name='reportaggregate',
            name='overlap_heatmap_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='overlap_heatmap_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
