# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0010_auto_20220930_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(default=-1)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Software name')),
                ('value', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('node_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('node_place', models.SmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pathogen_identification.SoftwareTreeNode')),
                ('software_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.SoftwareTree')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='softwaretree_nodes',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='softwaretree_nodes',
            name='software_tree',
        ),
        migrations.DeleteModel(
            name='SoftwareTree_nodes',
        ),
    ]
