# Generated by Django 4.2.16 on 2026-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0010_remove_reportgroup_clade_heatmap_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesourcefile',
            name='is_cache',
            field=models.BooleanField(default=False),
        ),
    ]
