# Generated by Django 4.2.16 on 2026-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0010_runremapmain_missing_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmain',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='run_controls', to='pathogen_identification.piproject_sample'),
        ),
    ]
