# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-22 15:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0010_auto_20221216_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(db_index=True, default='nameless_project', max_length=200, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', code='invalid_username', inverse_match=True)], verbose_name='Project name'),
        ),
    ]
