# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0011_auto_20220930_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='parameterset',
            name='leaf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.SoftwareTreeNode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
        migrations.AddField(
            model_name='submitted',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_fastq_input', to='pathogen_identification.ParameterSet'),
        ),
        migrations.AddField(
            model_name='processed',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.ParameterSet'),
        ),
    ]
