# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pathogen_identification", "0011_auto_20221222_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="runmain",
            name="last_modified",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
