# Generated by Django 4.2.16 on 2026-10-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0011_runmain_controls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwaretreenode',
            old_name='index',
            new_name='tree_index',
        ),
    ]
