# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-31 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0012_runmain_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='control_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piproject_sample',
            name='is_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runmain',
            name='data_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
