# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-01 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0012_auto_20221001_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaretreenode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
