# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-12 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0013_auto_20230331_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelevirRunQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed', models.BooleanField(default=False)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('args', models.CharField(blank=True, max_length=50, null=True)),
                ('input_reads', models.CharField(blank=True, max_length=50, null=True)),
                ('output_reads', models.CharField(blank=True, max_length=50, null=True)),
                ('output_reads_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.RunMain')),
            ],
            options={
                'ordering': ['run'],
            },
        ),
    ]
