# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-03 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0013_auto_20221001_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runmain',
            name='contig_classification_performed',
        ),
        migrations.RemoveField(
            model_name='runmain',
            name='read_classification_performed',
        ),
    ]
