# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-03 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0014_auto_20221003_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runmain',
            name='remap_performed',
        ),
    ]
