# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0014_televirrunqc'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaretree',
            name='model',
            field=models.IntegerField(default=0),
        ),
    ]
