# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0015_remove_runmain_remap_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piproject_sample',
            name='combinations',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
