# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0016_auto_20230822_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runmain',
            name='enrichment_args',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='runmain',
            name='host_depletion_args',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='runmain',
            name='remap_args',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
