# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0016_auto_20221003_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.Projects'),
        ),
    ]
