# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0017_parameterset_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmain',
            name='parameter_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='run_main', to='pathogen_identification.ParameterSet'),
        ),
        migrations.AddField(
            model_name='sampleqc',
            name='ParameterSet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sample_qc', to='pathogen_identification.ParameterSet'),
        ),
    ]
