# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-05 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0018_auto_20231121_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmain',
            name='run_type',
            field=models.IntegerField(default=0),
        ),
    ]
