# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0020_auto_20231207_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencesource',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
