# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0020_projects_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='piproject_sample',
            name='running_processes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='running_processes',
            field=models.IntegerField(default=0),
        ),
    ]
