# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0021_auto_20221010_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not started'), (1, 'Running'), (2, 'Finished'), (3, 'Error')], default=0),
        ),
    ]
