# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0021_auto_20231207_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmain',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
