# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0022_parameterset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='leaf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pathogen_identification.SoftwareTreeNode'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pathogen_identification.PIProject_Sample'),
        ),
    ]
