# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0022_runmain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreference',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
