# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0023_auto_20221011_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not started'), (1, 'Running'), (2, 'Finished'), (3, 'Error'), (4, 'Queued')], default=0),
        ),
        migrations.AlterField(
            model_name='runremapmain',
            name='merged_log',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='runremapmain',
            name='remap_plan',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
