# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-02 12:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0030_reference_specie_tag'),
        ('pathogen_identification', '0023_auto_20240104_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleFluProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='nameless_project', max_length=200, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', code='invalid_username', inverse_match=True)], verbose_name='Project name')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('insaflu_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insaflu_project', to='managing_files.Project')),
                ('raw_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.RawReference')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managing_files.Reference')),
                ('televir_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.Projects')),
            ],
        ),
    ]
