# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0024_auto_20221023_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runremapmain',
            name='method',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
