# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-02 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0024_telefluproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefluproject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telefluproject',
            name='last_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last change date'),
        ),
    ]
