# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0025_auto_20221023_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaretree',
            name='global_index',
            field=models.IntegerField(default=0),
        ),
    ]
