# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0025_auto_20240202_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='RawReferenceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_reference', to='pathogen_identification.RawReference')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_map', to='pathogen_identification.MetaReference')),
            ],
        ),
        migrations.AlterField(
            model_name='telefluproject',
            name='raw_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.MetaReference'),
        ),
    ]
