# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-27 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0026_auto_20221024_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemap_main',
            name='bai_file_path',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='referencemap_main',
            name='bam_file_path',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='referencemap_main',
            name='fai_file_path',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='referencemap_main',
            name='fasta_file_path',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
