# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0026_auto_20240202_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareference',
            name='file_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
