# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0027_metareference_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleFluSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teleflu_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.TeleFluProject')),
                ('televir_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample')),
            ],
        ),
    ]
