# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0027_auto_20221027_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalreport',
            name='bai_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='bam_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='mapped_scaffolds_index_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='mapped_scaffolds_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='ref_db',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='reference_assembly_paf',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='reference_index_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='reference_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
