# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0028_auto_20221029_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Mapped'), (1, 'Unmapped'), (2, 'Mapping')], default=1)),
                ('taxid', models.CharField(blank=True, max_length=100, null=True)),
                ('accid', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('classification_source', models.CharField(blank=True, max_length=15, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.RunMain')),
            ],
        ),
    ]
