# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0029_auto_20240205_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunReadsRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_reads_r1', models.CharField(blank=True, max_length=1000, null=True)),
                ('qc_reads_r2', models.CharField(blank=True, max_length=1000, null=True)),
                ('enriched_reads_r1', models.CharField(blank=True, max_length=1000, null=True)),
                ('enriched_reads_r2', models.CharField(blank=True, max_length=1000, null=True)),
                ('depleted_reads_r1', models.CharField(blank=True, max_length=1000, null=True)),
                ('depleted_reads_r2', models.CharField(blank=True, max_length=1000, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.RunMain')),
            ],
        ),
    ]
