# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-16 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pathogen_identification", "0029_rawreference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="softwaretree",
            options={"ordering": ["global_index"]},
        ),
    ]
