# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-06 14:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathogen_identification', '0030_runreadsregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='nameless_panel', max_length=200, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', code='invalid_username', inverse_match=True)], verbose_name='Panel name')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rawreference',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.ReferencePanel'),
        ),
    ]
