# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0031_auto_20240306_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepanel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='referencepanel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
