# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0032_auto_20240306_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepanel',
            name='project_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample'),
        ),
    ]
