# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0033_referencepanel_project_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='piproject_sample',
            name='panel_pk_string',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
