# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0034_piproject_sample_panel_pk_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmain',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.ReferencePanel'),
        ),
        migrations.AlterField(
            model_name='piproject_sample',
            name='panel_pk_string',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
