# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0035_auto_20240309_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepanel',
            name='panel_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencepanel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.ReferencePanel'),
        ),
    ]
