# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0036_auto_20240309_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepanel',
            name='icon',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, verbose_name='Icon'),
        ),
    ]
