# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0037_referencepanel_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmain',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
