# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-14 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0038_runmain_created_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefluMappedSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TelefluMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.SoftwareTreeNode')),
                ('teleflu_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.TeleFluProject')),
            ],
        ),
        migrations.AddField(
            model_name='teleflumappedsample',
            name='teleflu_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.TelefluMapping'),
        ),
        migrations.AddField(
            model_name='teleflumappedsample',
            name='teleflu_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.TeleFluSample'),
        ),
    ]
