# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0039_auto_20240314_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleflumapping',
            name='stacked_samples',
            field=models.ManyToManyField(to='pathogen_identification.TeleFluSample'),
        ),
    ]
