# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-28 11:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pathogen_identification", "0041_auto_20240326_1658"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceSourceFileMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="referencesourcefile",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="referencesourcefilemetadata",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pathogen_identification.ReferenceSourceFile",
            ),
        ),
    ]
