# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0042_auto_20240328_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawReferenceCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.CharField(blank=True, max_length=100, null=True)),
                ('accid', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('manual_insert', models.BooleanField(default=False)),
                ('standard_score', models.FloatField(blank=True, null=True)),
                ('family', models.ManyToManyField(blank=True, null=True, related_name='family', to='pathogen_identification.RawReference')),
                ('mapped_final_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.FinalReport')),
                ('mapped_raw_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.RawReference')),
                ('runs', models.ManyToManyField(blank=True, null=True, related_name='runs', to='pathogen_identification.RunMain')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogen_identification.PIProject_Sample')),
            ],
        ),
    ]
