# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-17 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0044_auto_20240417_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawReferenceCompound',
            new_name='RawReferenceCompoundModel',
        ),
    ]
