# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0045_auto_20240417_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawreferencecompoundmodel',
            name='selected_mapped_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
