# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0046_rawreferencecompoundmodel_selected_mapped_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreference',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
