# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0047_auto_20240417_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawreferencecompoundmodel',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
    ]
