# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0048_rawreferencecompoundmodel_run_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreferencecompoundmodel',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
