# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-03 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0049_auto_20240523_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawreferencecompoundmodel',
            name='ensemble_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawreferencecompoundmodel',
            name='global_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
