# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0051_rawreferencecompoundmodel_screening_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='updated_version',
            field=models.CharField(default='2.0.0', max_length=10),
        ),
    ]
