# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-05 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0052_projects_updated_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='updated_version',
            field=models.CharField(default='2.1.0', max_length=10),
        ),
    ]
