# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-04-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0053_auto_20240805_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='updated_version',
            field=models.CharField(default='2.2.0', max_length=10),
        ),
    ]
