# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-10-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0054_auto_20250403_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='updated_version',
            field=models.CharField(default='2.2.2', max_length=10),
        ),
    ]
