# Generated by Django 4.2.16 on 2026-02-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0055_alter_contigclassification_id_alter_finalreport_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwaretree',
            old_name='model',
            new_name='pipeline_type',
        ),
        migrations.AddField(
            model_name='softwaretreenode',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
