# Generated by Django 4.2.16 on 2026-02-20 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managing_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathogen_identification', '0001_initial'),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_extended', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('help_text', models.TextField(default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_extended', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareDefaultTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tested_all_defaults', models.BooleanField(default=False)),
                ('is_tested_televir_defaults', models.BooleanField(default=False)),
                ('televir_pipelines_available', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_default_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_extended', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('version_parameters', models.SmallIntegerField(default=0)),
                ('type_of_use', models.SmallIntegerField(default=0)),
                ('type_of_software', models.SmallIntegerField(default=0)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('can_be_on_off_in_pipeline', models.BooleanField(default=False)),
                ('is_to_run', models.BooleanField(default=True)),
                ('help_text', models.TextField(default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_settings', to=settings.AUTH_USER_MODEL)),
                ('pipeline_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_settings', to='settings.pipelinestep')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_settings', to='settings.technology')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('parameter', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('type_data', models.SmallIntegerField()),
                ('union_char', models.CharField(default='', max_length=10)),
                ('can_change', models.BooleanField(default=True)),
                ('sequence_out', models.SmallIntegerField()),
                ('range_available', models.CharField(default='', max_length=50)),
                ('range_max', models.CharField(default='', max_length=50)),
                ('range_min', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('not_set_value', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_to_run', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='datasets.dataset')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='managing_files.project')),
                ('project_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='managing_files.projectsample')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='managing_files.sample')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='settings.software')),
                ('televir_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='pathogen_identification.projects')),
                ('televir_project_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='televir_sample_parameter', to='pathogen_identification.piproject_sample')),
            ],
            options={
                'ordering': ['sequence_out'],
            },
        ),
    ]
