# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-04 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('parameter', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('type_data', models.SmallIntegerField()),
                ('union_char', models.CharField(default='', max_length=10)),
                ('can_change', models.BooleanField(default=True)),
                ('sequence_out', models.SmallIntegerField()),
                ('range_available', models.CharField(default='', max_length=50)),
                ('range_max', models.CharField(default='', max_length=50)),
                ('range_min', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ['sequence_out'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='settings.Software'),
        ),
    ]
