# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('managing_files', '0001_initial'),
        ('pathogen_identification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('parameter', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('type_data', models.SmallIntegerField()),
                ('union_char', models.CharField(default='', max_length=10)),
                ('can_change', models.BooleanField(default=True)),
                ('sequence_out', models.SmallIntegerField()),
                ('range_available', models.CharField(default='', max_length=50)),
                ('range_max', models.CharField(default='', max_length=50)),
                ('range_min', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('not_set_value', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_to_run', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='datasets.Dataset')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='managing_files.Project')),
                ('project_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='managing_files.ProjectSample')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='managing_files.Sample')),
            ],
            options={
                'ordering': ['sequence_out'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_extended', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('help_text', models.TextField(default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_extended', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('version_parameters', models.SmallIntegerField(default=0)),
                ('type_of_use', models.SmallIntegerField(default=0)),
                ('type_of_software', models.SmallIntegerField(default=0)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('can_be_on_off_in_pipeline', models.BooleanField(default=False)),
                ('is_to_run', models.BooleanField(default=True)),
                ('help_text', models.TextField(default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_settings', to=settings.AUTH_USER_MODEL)),
                ('pipeline_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_settings', to='settings.PipelineStep')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_extended', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='software',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_settings', to='settings.Technology'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='settings.Software'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='televir_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='pathogen_identification.Projects'),
        ),
    ]
