# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
