# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_parameter_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='type_of_use',
            field=models.SmallIntegerField(default=0),
        ),
    ]
