# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-09-12 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0015_auto_20200323_2050'),
        ('settings', '0004_software_type_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='project_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='managing_files.ProjectSample'),
        ),
    ]
