# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-10-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_parameter_project_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='name_extended',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='type_of_software',
            field=models.SmallIntegerField(default=0),
        ),
    ]
