# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-30 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0018_auto_20210120_1850'),
        ('settings', '0007_auto_20210117_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='managing_files.Sample'),
        ),
    ]
