# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-04-14 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_parameter_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='version_parameters',
            field=models.SmallIntegerField(default=0),
        ),
    ]
