# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-04-25 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_software_version_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
