# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-11-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_software_is_obsolete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name_extended', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('help_text', models.TextField(default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='software',
            name='can_be_on_off_in_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='software',
            name='help_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='software',
            name='is_to_run',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='software',
            name='pipeline_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_settings', to='settings.PipelineStep'),
        ),
    ]
