# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-12-24 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20211130_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='is_to_run',
            field=models.BooleanField(default=True),
        ),
    ]
