# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogen_identification', '0021_auto_20221010_1209'),
        ('settings', '0012_parameter_is_to_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='televir_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter', to='pathogen_identification.Projects'),
        ),
    ]
