# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-18 10:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managing_files", "0030_reference_specie_tag"),
        ("settings", "0014_auto_20221209_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="televir_project_sample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="televir_sample_parameter",
                to="pathogen_identification.PIProject_Sample",
            ),
        ),
    ]
