# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-16 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0015_parameter_televir_project_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareDefaultTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tested_all_defaults', models.BooleanField(default=False)),
                ('is_tested_televir_defaults', models.BooleanField(default=False)),
                ('televir_pipelines_available', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_default_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
