# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='type_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_files', to='managing_files.MetaKey'),
        ),
    ]
