# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import managing_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0002_auto_20171016_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='number_of_sequences',
            new_name='number_of_locus',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='scentific_name',
            new_name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='reference',
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_fasta',
            field=models.FileField(blank=True, max_length=600, null=True, upload_to=managing_files.models.reference_directory_path),
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_genbank',
            field=models.FileField(blank=True, max_length=600, null=True, upload_to=managing_files.models.reference_directory_path),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
