# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0002_uploadfiles_type_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='sample',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='number_files_to_process',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='samples',
            field=models.ManyToManyField(to='managing_files.Sample'),
        ),
    ]
