# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0002_auto_20171209_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Reference name'),
        ),
    ]
