# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0003_auto_20171026_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='hash_reference_fasta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='hash_reference_genbank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
