# Generated by Django 4.2.16 on 2026-08-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0003_alter_countvariations_id_alter_dataset_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processcontroler',
            old_name='name_sge_id',
            new_name='name_job_id',
        ),
    ]
