# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0004_auto_20171026_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='scientific_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
