# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0004_auto_20171221_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='is_samples_list',
        ),
    ]
