# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import fluwebvirus.formatChecker
import managing_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0005_auto_20171026_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='reference_fasta_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_genbank_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_fasta',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=managing_files.models.reference_directory_path),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_genbank',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=managing_files.models.reference_directory_path),
        ),
    ]
