# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0006_auto_20171028_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Up.Date'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='is_obsolete',
            field=models.BooleanField(default=False, verbose_name='Obsolete'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='number_of_locus',
            field=models.IntegerField(default=0, verbose_name='#Segments'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_fasta_name',
            field=models.CharField(default='', max_length=200, verbose_name='Fasta file'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_genbank_name',
            field=models.CharField(default='', max_length=200, verbose_name='Genbank file'),
        ),
    ]
