# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0006_remove_uploadfiles_is_first_fastq_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='attached_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='upload_files'),
        ),
    ]
