# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managing_files', '0007_auto_20171029_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='sample',
            name='date_sample',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='sample date'),
        ),
        migrations.AddField(
            model_name='sample',
            name='tag_names',
            field=models.ManyToManyField(to='managing_files.TagName'),
        ),
    ]
