# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0007_auto_20171228_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixedinfections',
            name='last_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='uploaded date'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='attached_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date attached'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date'),
        ),
    ]
