# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_virus', '0004_identifyvirus'),
        ('managing_files', '0008_auto_20171031_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='identify_virus',
            field=models.ManyToManyField(to='manage_virus.IdentifyVirus'),
        ),
    ]
