# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0008_auto_20171229_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='display_name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Display name'),
        ),
    ]
