# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0009_sample_identify_virus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletag',
            name='owner',
        ),
        migrations.AddField(
            model_name='sample',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='managing_files.DataSet'),
        ),
        migrations.DeleteModel(
            name='SampleTag',
        ),
    ]
