# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0009_reference_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='projectsample',
            name='count_variations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_samples', to='managing_files.CountVariations'),
        ),
        migrations.AlterField(
            model_name='projectsample',
            name='mixed_infections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_samples', to='managing_files.MixedInfections'),
        ),
        migrations.AlterField(
            model_name='projectsample',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_samples', to='managing_files.Project'),
        ),
        migrations.AlterField(
            model_name='projectsample',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_samples', to='managing_files.Sample'),
        ),
    ]
