# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0010_auto_20171101_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
