# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0011_sample_number_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='number_of_locus',
            field=models.IntegerField(default=0, verbose_name='#Locus'),
        ),
    ]
