# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0011_sample_is_obsolete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(blank=True, null=True, verbose_name='sample date'),
        ),
    ]
