# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0012_auto_20180124_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsample',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date attached'),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='is_deleted_in_file_system',
            field=models.BooleanField(default=False),
        ),
    ]
