# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import managing_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0012_auto_20171105_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='files',
        ),
        migrations.AddField(
            model_name='sample',
            name='file_name_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='file_name_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_valid_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_valid_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='path_name_1',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=managing_files.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='sample',
            name='path_name_2',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=managing_files.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
