# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managing_files', '0013_auto_20180124_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessControler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Submit job')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='Close date')),
                ('is_finished', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('name_sge_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_controles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
