# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0014_processcontroler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Sample Name'),
        ),
    ]
