# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0014_auto_20171107_1117'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sample',
            managers=[
                ('geo_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
