# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managing_files', '0015_auto_20171109_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKeyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='uploaded date')),
                ('value', models.CharField(default='value not needed', max_length=200)),
                ('description', models.TextField(default='')),
                ('meta_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_key_project', to='managing_files.MetaKey')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_key_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project__id', '-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='MetaKeyProjectSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='uploaded date')),
                ('value', models.CharField(default='value not needed', max_length=200)),
                ('description', models.TextField(default='')),
                ('meta_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_key_project_sample', to='managing_files.MetaKey')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_key_project_sample', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_sample__id', '-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='uploaded date')),
            ],
            options={
                'ordering': ['project__id', '-creation_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='metakeysample',
            options={'ordering': ['sample__id', '-creation_date']},
        ),
        migrations.AlterModelManagers(
            name='sample',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_finished',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='samples',
        ),
        migrations.AddField(
            model_name='project',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='managing_files.Reference'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date'),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_sample', to='managing_files.Project'),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_sample', to='managing_files.Sample'),
        ),
        migrations.AddField(
            model_name='metakeyprojectsample',
            name='project_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_key_project_sample', to='managing_files.ProjectSample'),
        ),
        migrations.AddField(
            model_name='metakeyproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_key_project', to='managing_files.Project'),
        ),
    ]
