# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-11-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0016_projectsample_is_mask_consensus_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='type_of_fastq',
            field=models.SmallIntegerField(default=0, verbose_name='File type'),
        ),
    ]
