# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0016_auto_20171113_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsample',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
