# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-03-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0018_auto_20210120_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='type_of_fastq',
            field=models.SmallIntegerField(default=-1, verbose_name='File type'),
        ),
    ]
