# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:24
from __future__ import unicode_literals

from django.db import migrations
import fluwebvirus.formatChecker
import managing_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0019_projectsample_is_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_fasta',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.reference_directory_path),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_genbank',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.reference_directory_path),
        ),
        migrations.AlterField(
            model_name='sample',
            name='path_name_1',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='sample',
            name='path_name_2',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='path_name',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.user_directory_path),
        ),
    ]
