# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-04-14 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0019_auto_20210323_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
