# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0020_auto_20171118_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='type_subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
