# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0021_sample_type_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsample',
            name='alert_first_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='alert_second_level',
            field=models.IntegerField(default=0),
        ),
    ]
