# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0023_auto_20171130_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tagname',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
