# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-10-24 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0023_auto_20210919_1627'),
        ('managing_files', '0024_auto_20211017_1225'),
    ]

    operations = [
    ]
