# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-10-24 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0025_merge_20211024_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date deleted'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_deleted_processed_fastq',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date fastq deleted'),
        ),
    ]
