# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-01-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0026_auto_20211024_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_sample_in_the_queue',
            field=models.BooleanField(default=False),
        ),
    ]
