# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-04-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0027_sample_is_sample_in_the_queue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='software',
            name='version_long',
            field=models.TextField(default=''),
        ),
    ]
