# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-06-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0028_auto_20220419_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixedinfections',
            name='last_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last change date'),
        ),
    ]
