# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-09-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0028_auto_20220419_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='type_subtype',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
