# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-12 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0028_auto_20220419_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='identify_virus',
        ),
    ]
