# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-09-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0029_auto_20220902_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='specie_tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
