# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_virus', '0001_initial'),
        ('managing_files', '0029_remove_sample_identify_virus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='identify_virus',
            field=models.ManyToManyField(to='manage_virus.IdentifyVirus'),
        ),
    ]
