# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-09-22 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0029_auto_20220607_1602'),
        ('managing_files', '0029_auto_20220902_1257'),
    ]

    operations = [
    ]
