# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0030_reference_specie_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsample',
            name='classification',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='type_subtype',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Classification'),
        ),
    ]
