# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-09-29 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0030_reference_specie_tag'),
        ('managing_files', '0030_merge_20220922_1717'),
    ]

    operations = [
    ]
