# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-28 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0030_auto_20220902_1353'),
        ('managing_files', '0029_auto_20220902_1257'),
    ]

    operations = [
    ]
