# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-27 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0031_merge_20221026_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixedinfections',
            name='last_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='uploaded date'),
        ),
    ]
