# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-09 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fluwebvirus.formatChecker
import managing_files.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managing_files', '0031_auto_20240208_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Primer set name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date')),
                ('primer_fasta', fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.reference_directory_path)),
                ('primer_fasta_name', models.CharField(default='', max_length=200, verbose_name='Fasta file')),
                ('hash_primer_fasta', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_pairs', fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.reference_directory_path)),
                ('primer_pairs_name', models.CharField(default='', max_length=200, verbose_name='Tabular file with primer pairs')),
                ('hash_primer_pairs', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('is_deleted_in_file_system', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Date attached')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Primer',
                'verbose_name_plural': 'Primers',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='primer',
            index=models.Index(fields=['name'], name='primer_name_idx'),
        ),
    ]
