# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0031_merge_20220928_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='specie_tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
