# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-23 09:03
from __future__ import unicode_literals

from django.db import migrations
import fluwebvirus.formatChecker
import managing_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0032_auto_20250509_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='primer_fasta',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.primer_directory_path),
        ),
        migrations.AlterField(
            model_name='primer',
            name='primer_pairs',
            field=fluwebvirus.formatChecker.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=managing_files.models.primer_directory_path),
        ),
    ]
