# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_files', '0032_auto_20221027_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='specie_tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
