# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_virus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seqvirus',
            old_name='file_name',
            new_name='file',
        ),
        migrations.AddField(
            model_name='seqvirus',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
