# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_virus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqvirus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
