# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_virus', '0002_auto_20171101_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='abricate_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
