# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_virus', '0003_uploadfile_abricate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifyVirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('coverage', models.CharField(blank=True, max_length=10, null=True)),
                ('identity', models.CharField(blank=True, max_length=10, null=True)),
                ('seq_virus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identify_virus', to='manage_virus.SeqVirus')),
            ],
        ),
    ]
