# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_virus', '0004_identifyvirus'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifyvirus',
            name='acession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
