# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_virus', '0005_identifyvirus_acession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifyvirus',
            name='acession',
        ),
    ]
