# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.TextField(blank=True, max_length=100)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('only_view_project', models.BooleanField(default=False)),
                ('queue_name_sge', models.CharField(blank=True, max_length=20, null=True)),
                ('max_references', models.IntegerField(default=30)),
                ('max_samples', models.IntegerField(default=500)),
                ('max_file_size_fastq', models.IntegerField(default=50000000)),
                ('max_length_reference_fasta', models.IntegerField(default=20000)),
                ('max_sequence_reference', models.IntegerField(default=20)),
                ('sge_seq_id_g', models.IntegerField(default=1)),
                ('sge_seq_id_s', models.IntegerField(default=1)),
                ('sge_seq_id_l', models.IntegerField(default=1)),
                ('sge_seq_id_r', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
