# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_references',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_samples',
            field=models.IntegerField(default=500),
        ),
    ]
