# Generated by Django 4.2.16 on 2026-07-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
