# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0002_auto_20171221_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_file_size_fastq',
            field=models.IntegerField(default=50000000),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_length_reference_fasta',
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_sequence_reference',
            field=models.IntegerField(default=20),
        ),
    ]
