# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0004_profile_only_view_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='queue_name_sge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
