# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0005_profile_queue_name_sge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sge_seq_id',
            field=models.IntegerField(default=0),
        ),
    ]
