# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-04-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0006_profile_sge_seq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sge_seq_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='sge_seq_id_g',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sge_seq_id_l',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sge_seq_id_r',
            field=models.IntegerField(default=1),
        ),
    ]
