# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-01-18 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0007_auto_20200411_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sge_seq_id_s',
            field=models.IntegerField(default=1),
        ),
    ]
